"""empty message

Revision ID: 3f87897749d3
Revises: bcd3e2801acc
Create Date: 2020-06-01 16:59:43.564303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f87897749d3'
down_revision = 'bcd3e2801acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_menu', 't_menu', ['pid'], ['id'])
    op.add_column('t_table', sa.Column('rid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_table', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_table', type_='foreignkey')
    op.drop_column('t_table', 'rid')
    op.drop_constraint(None, 't_menu', type_='foreignkey')
    # ### end Alembic commands ###
