"""empty message

Revision ID: 72be723d94de
Revises: 97ef6c6f7208
Create Date: 2020-06-01 17:42:48.821560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72be723d94de'
down_revision = '97ef6c6f7208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='t_menu')
    op.drop_table('t_menu')
    op.add_column('t_table', sa.Column('rid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_table', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_table', type_='foreignkey')
    op.drop_column('t_table', 'rid')
    op.create_table('t_menu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 't_menu', ['name'], unique=True)
    # ### end Alembic commands ###
