"""empty message

Revision ID: 8dfb5002ecc4
Revises: 2d77eee41be4
Create Date: 2020-05-22 21:33:37.074946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfb5002ecc4'
down_revision = '2d77eee41be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_table', sa.Column('craete_time', sa.DateTime(), nullable=True))
    op.add_column('t_table', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_table', 'update_time')
    op.drop_column('t_table', 'craete_time')
    # ### end Alembic commands ###
