"""empty message

Revision ID: 97ef6c6f7208
Revises: a9c36b3871ac
Create Date: 2020-06-01 17:35:36.810190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ef6c6f7208'
down_revision = 'a9c36b3871ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_menu', 't_menu', ['pid'], ['id'])
    op.add_column('t_table', sa.Column('rid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_table', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_table', type_='foreignkey')
    op.drop_column('t_table', 'rid')
    op.drop_constraint(None, 't_menu', type_='foreignkey')
    # ### end Alembic commands ###
